### ISSUE TITLE
dynamic uri source for images

### ISSUE THREAD

**Issue by bruxalldev** [davidrenji/rn-fade-carousel#1]
Hi is it possible to parse dynamic urls through the slider 

ie: <image source={uri: https://image_path.jpg} />

I've tried but it spits out incorrect source type

Thanks

**Comment by davidrenji** [comment]
Hi sorry for the late response.
It should work with dynamic urls, but in that case it should be:
<Image source={{uri: 'https://image_path.jpg'}} />
